### ISSUE TITLE
USB Power protection not working on Lich after Firmware 22.4

### ISSUE THREAD

**Issue by xustafu** [RebelTechnology/OpenWare#80]
USB host devices are not powered from Lich USB connector.
We tested  protection IC MIC2005 and found that Enable pin is always low. Even with fault pin being low.
This behaviour can be reproduced in 22.4 and 22.5 RC1 firmwares. Testing in 22.2 it works properly.

**Comment by antisvin** [comment]
I think this is the reason why:
https://github.com/RebelTechnology/OpenWare/commit/7316ce662d08318238059e76ac903a58202a8228#diff-b34296f98f477a967e4c7bc1c3aa3bdb27e759400c7200c1805076304c2e2c27L390-L414

It looks like during refactoring that file was removed from Lich sources and moved to Sources directory to be used with multiple projects. At that time the code for toggling USB_HOST_PWR_EN pin was removed

**Comment by marsus** [comment]
ooh yes, that makes sense. Thank you @antisvin !
