### ISSUE TITLE
missing poly_key_pressure methods in MidiMessage.h

### ISSUE THREAD

**Issue by dromer** [RebelTechnology/OpenWare#83]
I'm trying to add POLY_KEY_PRESSURE support to Heavy, however specific methods for this are missing: 
https://github.com/RebelTechnology/OpenWare/blob/master/Source/MidiMessage.h

Right now for the input I'm simply using this (as we just need `data[2]` and `data[1]`), but it looks a bit odd:

```c++
    case POLY_KEY_PRESSURE:
      context->sendMessageToReceiverV
  (HV_HASH_POLYTOUCHIN, 0, "fff"
   (float)msg.getChannelPressure(),
   (float)msg.getStatus(),
   (float)msg.getChannel());
      break
```

For the ouput I'll have to manually come up with a suitable construct, but a `MidiMessage::pt` would be helpful.

**Comment by antisvin** [comment]
I think something like this would work:

```
  static MidiMessage kp(uint8_t ch, uint8_t note, uint8_t pressure){
      return MidiMessage(USB_COMMAND_POLY_KEY_PRESSURE, POLY_KEY_PRESSURE|(ch&0xf), note&0x7f, pressure&0x7f);
  }
```

and a few related functions like

```
  bool isPolyKeyPressure(){
    return (data[1] & MIDI_STATUS_MASK) == POLY_KEY_PRESSURE;
  }

  uint8_t getPressure(){
    return data[3];
  }
```

**Comment by antisvin** [comment]
BTW, this actually belongs to OwlProgram repo as it handles MIDI separately. I.e. its respective header file is https://github.com/RebelTechnology/OwlProgram/blob/develop/LibSource/MidiMessage.h

**Comment by dromer** [comment]
@antisvin hmm, I see. I didn't realize that there was such code duplication with OwlProgram.

**Comment by dromer** [comment]
@antisvin hmm, I see. I didn't realize that there was such code duplication with OwlProgram.

**Comment by antisvin** [comment]
Well firmware and patches are compiled and running separately from each other, so that's not surprising. I'd rather see MIDI stuff moved to a standalone library too. There are a few other things that are shared and could live in a separate repo (program vector definition, service calls statuses). But this is a bit off-topic.

**Comment by dromer** [comment]
So at the moment, for completeness, this should be added to both?

**Comment by antisvin** [comment]
Yeah, they are generally kept in sync. But note that firmware would not do anything with poly pressure, so in practice this would make no difference other than prevent us from accidentally lose those changes if we copy the MIDI headers in the opposite directions.

**Comment by pingdynasty** [comment]
> So at the moment, for completeness, this should be added to both?

There is already MidiMessage::getPolyKeyPressure() and ::isPolyKeyPressure() in OwlProgram, see https://github.com/RebelTechnology/OwlProgram/blob/develop/LibSource/MidiMessage.h#L75
I assume this is where you need it @dromer, and not in the firnware?

I will bring the OpenWare copy up to date.

**Comment by dromer** [comment]
@pingdynasty you can close this thread. I should've looked at OwlProgram and work with that instead. Thnx for the input guys.
